# Generated by Django 4.2.3 on 2023-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_options_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_job',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phon_number',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
