# Generated by Django 4.2.3 on 2023-08-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userprofile_current_job_userprofile_phon_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='companyName',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phon_number',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
