# Generated by Django 4.2.6 on 2023-11-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_img_user_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='imgage',
            new_name='image',
        ),
    ]
