# Generated by Django 4.2.6 on 2023-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_userprofile_currently_studying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='companyName',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_job',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phon_number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
