# Generated by Django 4.2.6 on 2023-11-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_userprofile_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='companyName',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_job',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currently_studying',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phon_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
