# Generated by Django 4.2.6 on 2023-11-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_userprofile_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default=' ', max_length=10, null=True),
        ),
    ]
