# Generated by Django 4.2.7 on 2024-11-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_message_user_alter_room_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile'),
        ),
    ]
